- label: Home
  route: /

- label: Blog
  route: /blog

- label: Cronograma
  route: /cronogramabb1bb2

- label: Lista BB
  route: /listapresencabb

- label: Conteudo BB
  route: /conteudobb

- label: Quiz
  route: /quiz

- label: Glicolise
  route: /glicolise
  
# - label: Portfolio
#   route: /port