- label: Home
  route: /

- label: Blog
  route: /blog

- label: Cronograma Nutrição
  route: /cronogramanutrição

- label: Lista BB
  route: /listapresencabb

- label: Conteudo BB
  route: /conteudobb

- label: Cronograma AG1AG2
  route: /cronogramaag1ag2

- label: CronogramaFA01
  route: /cronogramafa01

- label: Quiz
  route: /quiz

- label: Como Estudo
  route: /comoestudo

- label: Lista FA
  route: /listapresencafa01

# Item 10
- label: Conteudo FA
  route: /conteudofa01

# Item 11
- label: Lista BL
  route: /listapresencabl01
  
# - label: Portfolio
#   route: /port